name: mongo

on:
  push:
    branches: [ mongo ]

jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@master
      - uses: supercharge/mongodb-github-action@1.3.0
      - name: check mongodb
        run: |
          sudo netstat -tlnp
          mongo
          
