name: mongo

on:
  push:
    branches: [ mongo ]

jobs:
  build:
    runs-on: ubuntu-18.04
    services:
      mongodb:
        image: mongo
        ports:
        - 27017:27017
    steps:
      - uses: actions/checkout@master
      - name: check mongodb
        run: | 
          sudo netstat -tlnp 
          
