name: mongo

on:
  push:
    branches: [ mongo ]

jobs:
  build:
    runs-on: ubuntu-16.04
    steps:
      - uses: actions/checkout@master
      - uses: supercharge/mongodb-github-action@1.3.0
      - name: Install mongodb
        run: |
            sudo which mongo
            sudo service mongodb status
          
