name: mongo

on:
  push:
    branches: [ mongo ]

jobs:
  build:
    runs-on: ubuntu-16.04
    steps:
      - uses: actions/checkout@master
      - name: Install mongodb
        run: |
          sudo apt-get update
          sudo apt-get install -y mongodb
          
