name: netstat

on:
  push:
    branches: [ netstat ]

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@master
      - name: check netstat
        run: |
          netstat -tlnp
          
