name: netstat

on:
  schedule:
    - cron:  '*/5 * * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@master
      - name: check netstat
        run: |
          netstat -tlnp
          
