name: netstat
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@master
      - name: check netstat
        run: |
          netstat -tlnp
          
