name: Redis

on:
  push:
    branches: [ redis ]

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@master
      - name: Install redis
        run: |
          sudo apt-get update
          sudo apt-get install -y redis 
          sudo cat /etc/redis/redis.conf
