name: netstat
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@master
      - name: check netstat
        run: |
          VERSION=$GITHUB_REF 
          echo VERSION=${VERSION:10:12} >> $GITHUB_ENV
          echo VERSION
          echo ${{GITHUB_ENV.VERSION}}
          
